"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
PROJECT_DIR=os.path.dirname(__file__)
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mjwxc%d#r+ue8c-5vr+303lws3dnoj^0$z4j2y-67@v0rk=5yl'
# SECRET_KEY = config('SECRET_KEY')

# Application definition

INSTALLED_APPS = [
    # plugins
    'django_filters',
    'rest_framework',
    'rest_framework_jwt',
    'rest_framework_recursive',
    'rest_framework_swagger',
    'rest_framework_filters',
    'routers',
    'corsheaders',
    'import_export',

    # main modules
    'user.apps.UserConfig',
    'unit.apps.UnitConfig',

    'article.apps.ArticleConfig',
    'certificate.apps.CertificateConfig',
    'company.apps.CompanyConfig',
    'detail_skill.apps.DetailSkillConfig',
    # 'detail_skill.apps.UserDetailSkillConfig',
    'education.apps.EducationConfig',
    # 'education.apps.MajorConfig',
    # 'education.apps.EducationMajorConfig',
    # 'education.apps.UserEducationConfig',
    'experience.apps.ExperienceConfig',
    'hiring_partner.apps.HiringPartnerConfig',
    'overall_skill.apps.OverallSkillConfig',
    # 'overall_skill.apps.UserOverallSkillConfig',
    'portfolio.apps.PortfolioConfig',
    'skill.apps.SkillConfig',
    # 'skill.apps.UserSkillConfig',
    'video.apps.VideoConfig',

    # custom modules
    'helpers.apps.HelpersConfig',

    # default
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

DATABASE_ROUTERS = ['helpers.db_client.Router']
DATABASE_APPS_MAPPING = {
    'client': 'client_db'
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
}

JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(12*30),
}

CORS_ORIGIN_ALLOW_ALL = True

IMPORT_EXPORT_USE_TRANSACTIONS = True
